controller:
  nodeSelector:
    jenkinsType: controller
    dedicated: jenkins
    eks.amazonaws.com/capacityType: ON_DEMAND
  tolerations:
    - key: dedicated
      operator: Equal
      value: jenkins
      effect: NoSchedule
    - key: jenkinsType
      operator: Equal
      value: controller
      effect: NoSchedule
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - aws-credentials
    - configuration-as-code
  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |-
        jenkins:
          systemMessage: "Welcome to the EKS Jenkins Cluster!"

agent:
  customJenkinsLabels:
    - "my-gp3-agent"
  nodeSelector:
    jenkinsType: agent
    dedicated: jenkins
    eks.amazonaws.com/capacityType: SPOT
  tolerations:
    - key: dedicated
      operator: Equal
      value: jenkins
      effect: NoSchedule
    - key: jenkinsType
      operator: Equal
      value: agent
      effect: NoSchedule
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"
  workspaceVolume:
    type: GenericEphemeralVolume
    storageClassName: gp3
    accessModes: ReadWriteOnce
    requestsSize: 15Gi
  yamlTemplate: |-
    apiVersion: v1
    kind: Pod
    spec:
      tolerations:
        - key: dedicated
          operator: Equal
          value: jenkins
          effect: NoSchedule
        - key: jenkinsType
          operator: Equal
          value: agent
          effect: NoSchedule
      initContainers:
        - name: ebs-permission-fix
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /home/jenkins/agent"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: workspace-volume
              mountPath: /home/jenkins/agent